services:   
  oauth-api:
    image: oauth-api:latest
    build:
      context: ./
      dockerfile: Dockerfile      
    container_name: oauth-api
    
    ports:
      - "3004:3004"
    env_file:
      - .env

networks:
  default:
    external: 
      name: boeingnetwork
