version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db
    networks:
      - banknet

  account-api:
    build:
      context: ./  # ✅ Dockerfile is inside this folder
      dockerfile: Dockerfile 
    container_name: account-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - banknet

volumes:
  mongo_data:

networks:
  banknet:
    driver: bridge
